language: node_js
sudo: required
dist: trusty
cache:
  directories:
    - server/node_modules
    - client/node_modules
node_js: 7
addons:
  postgresql: "9.5"
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
env:
  global:
    - "CXX='g++-4.8'"
script:
  - cd server && npm install && npm run lint && npm test
  - cd .. 
  - cd client && npm install && npm run lint:t && npm run test:t 