language: node_js
sudo: required
dist: trusty
cache:
  directories:
    - server/node_modules
    - client/node_modules
node_js: 7
addons:
  postgresql: "9.5"
  firefox: latest
before_install: 
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
script:
  - cd server && npm install && npm run lint && npm test
  - cd .. 
  - cd client && npm install && npm run lint:t && npm run test:t 